version: 0
allowPullRequests: public
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.reopened
          - push
          - pull_request.synchronize
    payload:
      maxRunTime: 3600
      image: djmitche/rust-hawk-test:1.35.0@sha256:b4d60deff348ed8091fd1e431ac7d497aa6881b7fcbee56bf6272cb540f4b35a
      command:
        - /bin/bash
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo &&
          cd repo &&
          git config advice.detachedHead false &&
          git checkout {{event.head.sha}} &&
          cargo test --features="use_ring" --no-default-features &&
          cargo test --features="use_openssl" --no-default-features &&
          cargo fmt -- --check &&
          cargo clippy
    metadata:
      name: Tests
      description: Run tests
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
